# -*- coding: utf-8 -*-
"""multiplication table calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBejezVPFtalf_85COn6odyQ2piuxVEv

# Calculator
"""

print('Bem-Vindo a calcualdora de tabuada')

numero = int(input("Digite um número entre 1 e 10 para ver a tabuada: "))

if 1 <= numero <= 10:
  print(f"Tabuada do {numero}:")
  for i in range(1, 11):
        resultado = numero * i
        print(f"{numero} x {i} = {resultado}")
else:
    print("Por favor, digite um número válido entre 1 e 10.")