# -*- coding: utf-8 -*-
"""Profissao_Analista_de_dados_M1_Exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNar82cE0rb2VdXa4sQG9fqYTNPKiAnq

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Variáveis & Tipos de Dados
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Introdução ao Google Colab;</li>
  <li>Variáveis;</li>
  <li>Números;</li>
  <li><i>Strings;</i></li>
  <li>Boleanos.</li>
</ol>

---

# **Exercícios**

## 1\. Google Colab

Crie uma célula de código que escreva o texto "Olá mundo!", utilize o comando `print`.

Crie uma célua de texto e adicione uma imagem.

---

## 2\. Números

Preencha as células de código para preencher os valores de (A), (B) e (C) na tabela de ticket médio abaixo:

<br>

| Dia   | Valor Total Vendas | Qtd Total Vendas | Ticket Medio |
|-------|--------------------|------------------|--------------|
| 19/01 | (A)                | 3                | 320.52       |
| 20/01 | 834.47             | (B)              | 119.21       |
| 23/01 | 15378.12           | 5                | (C)          |
"""

# (A)

qtd_vendas = 3
tkt_medio = 320.52

A = qtd_vendas * tkt_medio
print(A)

# (B)

valor_vendas = 834.47
tkt_medio = 119.21

B = valor_vendas / tkt_medio
print(B)

# (C)

valor_vendas = 15378.12
total_vendas = 5

c = valor_vendas / total_vendas
print(c)

"""---

## 3\. Strings

Aplique três métodos distintos na *string* abaixo, você pode conferir alguns métodos neste [link](https://www.w3schools.com/python/python_ref_string.asp):
"""

cancao = 'roda mundo, roda gigante, roda moinho, roda pião.'

new_cancao = cancao.replace('roda', 'gira')
print(new_cancao)

cancao = 'roda mundo, roda gigante, roda moinho, roda pião.'

print(cancao.upper())

cancao = 'roda mundo, roda gigante, roda moinho, roda pião.'

X = " - ".join(cancao)
print(X)

"""Extraia da string abaixo o valor da taxa **selic** na variável `selic` e o valor do **ano** na variavel `ano`. Imprima os valores na tela."""

noticia = 'Selic vai a 2,75% e supera expectativas; é a primeira alta em 6 anos.'

inicio_selic = noticia.find('2,75%')
fim_selic = inicio_selic + len('2,75%')
selic = noticia[inicio_selic:fim_selic]
print(selic)


inicio_ano = noticia.find('em ') + len('em ')
fim_ano = inicio_ano + len('6 ')
ano = noticia[inicio_ano:fim_ano]
print(ano)

"""---

## 4\. Booleanos

Utilize a tabela da verdade para responder: qual o valor da variável x?
"""

a = False
b = True

x = not a & b

# not a & b é 'True & False', que é False. Portanto, a variavel X é False.